# Site settings
title: Everything's Comin' Up Sallis
email: jason@sall.is
description: ""
baseurl: ""
url: "http://sall.is"
twitter_username: jsallis
github_username:  jsallis

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /posts/:year/:month/:title
